/**
 * Catálogo 9 — complementos y packs (c9-).
 * Generado por scripts/_gen-catalog9.mjs
 */
import { buildCatalogFromNames, CAT_META } from "./catalog-builder.mjs";

export const CATALOG_9_CATEGORIES = [];

const NAMES = {
  "informatica": [
    "Lenovo Cargador USB-C 65W — compatibilidad universal",
    "Lenovo Cargador USB-C 65W — 65W PD",
    "Lenovo Cargador USB-C 65W — 100W PD",
    "Lenovo Cargador USB-C 65W — negro",
    "Lenovo Cargador USB-C 65W — gris espacial",
    "Lenovo Cargador USB-C 65W — pack 2",
    "Lenovo Cargador USB-C 65W — garantía 24 meses",
    "Lenovo Cargador USB-C 65W — marca original",
    "Lenovo Funda rígida 15 — compatibilidad universal",
    "Lenovo Funda rígida 15 — 65W PD",
    "Lenovo Funda rígida 15 — 100W PD",
    "Lenovo Funda rígida 15 — negro",
    "Lenovo Funda rígida 15 — gris espacial",
    "Lenovo Funda rígida 15 — pack 2",
    "Lenovo Funda rígida 15 — garantía 24 meses",
    "Lenovo Funda rígida 15 — marca original",
    "Lenovo Hub USB-A legacy — compatibilidad universal",
    "Lenovo Hub USB-A legacy — 65W PD",
    "Lenovo Hub USB-A legacy — 100W PD",
    "Lenovo Hub USB-A legacy — negro",
    "Lenovo Hub USB-A legacy — gris espacial",
    "Lenovo Hub USB-A legacy — pack 2",
    "Lenovo Hub USB-A legacy — garantía 24 meses",
    "Lenovo Hub USB-A legacy — marca original",
    "Lenovo Adaptador Ethernet USB-C — compatibilidad universal",
    "Lenovo Adaptador Ethernet USB-C — 65W PD",
    "Lenovo Adaptador Ethernet USB-C — 100W PD",
    "Lenovo Adaptador Ethernet USB-C — negro",
    "Lenovo Adaptador Ethernet USB-C — gris espacial",
    "Lenovo Adaptador Ethernet USB-C — pack 2",
    "Lenovo Adaptador Ethernet USB-C — garantía 24 meses",
    "Lenovo Adaptador Ethernet USB-C — marca original",
    "Lenovo Webcam cover pack — compatibilidad universal",
    "Lenovo Webcam cover pack — 65W PD",
    "Lenovo Webcam cover pack — 100W PD",
    "Lenovo Webcam cover pack — negro",
    "Lenovo Webcam cover pack — gris espacial",
    "Lenovo Webcam cover pack — pack 2",
    "Lenovo Webcam cover pack — garantía 24 meses",
    "Lenovo Webcam cover pack — marca original",
    "Lenovo Limpiador pantalla kit — compatibilidad universal",
    "Lenovo Limpiador pantalla kit — 65W PD"
  ],
  "perifericos": [
    "Logitech Recambio feet ratón — PTFE",
    "Logitech Recambio feet ratón — español ISO",
    "Logitech Recambio feet ratón — ANSI",
    "Logitech Recambio feet ratón — negro",
    "Logitech Recambio feet ratón — blanco",
    "Logitech Recambio feet ratón — pack 4",
    "Logitech Recambio feet ratón — gaming",
    "Logitech Recambio feet ratón — ofimática",
    "Logitech Cable paracord USB — PTFE",
    "Logitech Cable paracord USB — español ISO",
    "Logitech Cable paracord USB — ANSI",
    "Logitech Cable paracord USB — negro",
    "Logitech Cable paracord USB — blanco",
    "Logitech Cable paracord USB — pack 4",
    "Logitech Cable paracord USB — gaming",
    "Logitech Cable paracord USB — ofimática",
    "Logitech Switch set mecánico — PTFE",
    "Logitech Switch set mecánico — español ISO",
    "Logitech Switch set mecánico — ANSI",
    "Logitech Switch set mecánico — negro",
    "Logitech Switch set mecánico — blanco",
    "Logitech Switch set mecánico — pack 4",
    "Logitech Switch set mecánico — gaming",
    "Logitech Switch set mecánico — ofimática",
    "Logitech Lubricante switches — PTFE",
    "Logitech Lubricante switches — español ISO",
    "Logitech Lubricante switches — ANSI",
    "Logitech Lubricante switches — negro",
    "Logitech Lubricante switches — blanco",
    "Logitech Lubricante switches — pack 4",
    "Logitech Lubricante switches — gaming",
    "Logitech Lubricante switches — ofimática",
    "Logitech Tapas side buttons — PTFE",
    "Logitech Tapas side buttons — español ISO",
    "Logitech Tapas side buttons — ANSI",
    "Logitech Tapas side buttons — negro",
    "Logitech Tapas side buttons — blanco",
    "Logitech Tapas side buttons — pack 4",
    "Logitech Tapas side buttons — gaming",
    "Logitech Tapas side buttons — ofimática",
    "Logitech Alfombrilla rigida — PTFE",
    "Logitech Alfombrilla rigida — español ISO"
  ],
  "componentes-pc": [
    "Noctua Splitters PWM — 120mm",
    "Noctua Splitters PWM — 140mm",
    "Noctua Splitters PWM — ATX",
    "Noctua Splitters PWM — mATX",
    "Noctua Splitters PWM — negro",
    "Noctua Splitters PWM — pack",
    "Noctua Splitters PWM — Gen5",
    "Noctua Splitters PWM — PWM",
    "Noctua Adaptador 8 a 8 pin — 120mm",
    "Noctua Adaptador 8 a 8 pin — 140mm",
    "Noctua Adaptador 8 a 8 pin — ATX",
    "Noctua Adaptador 8 a 8 pin — mATX",
    "Noctua Adaptador 8 a 8 pin — negro",
    "Noctua Adaptador 8 a 8 pin — pack",
    "Noctua Adaptador 8 a 8 pin — Gen5",
    "Noctua Adaptador 8 a 8 pin — PWM",
    "Noctua Soporte SSD M.2 — 120mm",
    "Noctua Soporte SSD M.2 — 140mm",
    "Noctua Soporte SSD M.2 — ATX",
    "Noctua Soporte SSD M.2 — mATX",
    "Noctua Soporte SSD M.2 — negro",
    "Noctua Soporte SSD M.2 — pack",
    "Noctua Soporte SSD M.2 — Gen5",
    "Noctua Soporte SSD M.2 — PWM",
    "Noctua Brackets radiador 360 — 120mm",
    "Noctua Brackets radiador 360 — 140mm",
    "Noctua Brackets radiador 360 — ATX",
    "Noctua Brackets radiador 360 — mATX",
    "Noctua Brackets radiador 360 — negro",
    "Noctua Brackets radiador 360 — pack",
    "Noctua Brackets radiador 360 — Gen5",
    "Noctua Brackets radiador 360 — PWM",
    "Noctua Filtro polvo frontal — 120mm",
    "Noctua Filtro polvo frontal — 140mm",
    "Noctua Filtro polvo frontal — ATX",
    "Noctua Filtro polvo frontal — mATX",
    "Noctua Filtro polvo frontal — negro",
    "Noctua Filtro polvo frontal — pack",
    "Noctua Filtro polvo frontal — Gen5",
    "Noctua Filtro polvo frontal — PWM",
    "Noctua Tornillería caja — 120mm",
    "Noctua Tornillería caja — 140mm"
  ],
  "telefonia": [
    "Apple Pack cristal templado — iPhone 16 Pro",
    "Apple Pack cristal templado — Galaxy S25",
    "Apple Pack cristal templado — Pixel 10",
    "Apple Pack cristal templado — negro",
    "Apple Pack cristal templado — transparente",
    "Apple Pack cristal templado — dual SIM",
    "Apple Pack cristal templado — 5G",
    "Apple Pack cristal templado — pack ahorro",
    "Apple Cargador pared 45W — iPhone 16 Pro",
    "Apple Cargador pared 45W — Galaxy S25",
    "Apple Cargador pared 45W — Pixel 10",
    "Apple Cargador pared 45W — negro",
    "Apple Cargador pared 45W — transparente",
    "Apple Cargador pared 45W — dual SIM",
    "Apple Cargador pared 45W — 5G",
    "Apple Cargador pared 45W — pack ahorro",
    "Apple Cable USB-C 2m — iPhone 16 Pro",
    "Apple Cable USB-C 2m — Galaxy S25",
    "Apple Cable USB-C 2m — Pixel 10",
    "Apple Cable USB-C 2m — negro",
    "Apple Cable USB-C 2m — transparente",
    "Apple Cable USB-C 2m — dual SIM",
    "Apple Cable USB-C 2m — 5G",
    "Apple Cable USB-C 2m — pack ahorro",
    "Apple Soporte coche magnético — iPhone 16 Pro",
    "Apple Soporte coche magnético — Galaxy S25",
    "Apple Soporte coche magnético — Pixel 10",
    "Apple Soporte coche magnético — negro",
    "Apple Soporte coche magnético — transparente",
    "Apple Soporte coche magnético — dual SIM",
    "Apple Soporte coche magnético — 5G",
    "Apple Soporte coche magnético — pack ahorro",
    "Apple Funda antigolpes — iPhone 16 Pro",
    "Apple Funda antigolpes — Galaxy S25",
    "Apple Funda antigolpes — Pixel 10",
    "Apple Funda antigolpes — negro",
    "Apple Funda antigolpes — transparente",
    "Apple Funda antigolpes — dual SIM",
    "Apple Funda antigolpes — 5G",
    "Apple Funda antigolpes — pack ahorro",
    "Apple Tarjeta microSD 256 — iPhone 16 Pro",
    "Apple Tarjeta microSD 256 — Galaxy S25"
  ],
  "tablets": [
    "Apple Funda teclado BT — 11 pulgadas",
    "Apple Funda teclado BT — 12 pulgadas",
    "Apple Funda teclado BT — 13 pulgadas",
    "Apple Funda teclado BT — WiFi",
    "Apple Funda teclado BT — 5G",
    "Apple Funda teclado BT — rosa",
    "Apple Funda teclado BT — negro",
    "Apple Funda teclado BT — pack",
    "Apple Cap punta fina — 11 pulgadas",
    "Apple Cap punta fina — 12 pulgadas",
    "Apple Cap punta fina — 13 pulgadas",
    "Apple Cap punta fina — WiFi",
    "Apple Cap punta fina — 5G",
    "Apple Cap punta fina — rosa",
    "Apple Cap punta fina — negro",
    "Apple Cap punta fina — pack",
    "Apple Protector mate — 11 pulgadas",
    "Apple Protector mate — 12 pulgadas",
    "Apple Protector mate — 13 pulgadas",
    "Apple Protector mate — WiFi",
    "Apple Protector mate — 5G",
    "Apple Protector mate — rosa",
    "Apple Protector mate — negro",
    "Apple Protector mate — pack",
    "Apple Soporte mesa — 11 pulgadas",
    "Apple Soporte mesa — 12 pulgadas",
    "Apple Soporte mesa — 13 pulgadas",
    "Apple Soporte mesa — WiFi",
    "Apple Soporte mesa — 5G",
    "Apple Soporte mesa — rosa",
    "Apple Soporte mesa — negro",
    "Apple Soporte mesa — pack",
    "Apple Hub USB-C tablet — 11 pulgadas",
    "Apple Hub USB-C tablet — 12 pulgadas",
    "Apple Hub USB-C tablet — 13 pulgadas",
    "Apple Hub USB-C tablet — WiFi",
    "Apple Hub USB-C tablet — 5G",
    "Apple Hub USB-C tablet — rosa",
    "Apple Hub USB-C tablet — negro",
    "Apple Hub USB-C tablet — pack",
    "Apple Funda niños EVA — 11 pulgadas",
    "Apple Funda niños EVA — 12 pulgadas"
  ],
  "gaming": [
    "Sony Grip silicona mando — PS5",
    "Sony Grip silicona mando — Xbox Series",
    "Sony Grip silicona mando — Switch 2",
    "Sony Grip silicona mando — PC",
    "Sony Grip silicona mando — Steam Deck",
    "Sony Grip silicona mando — negro",
    "Sony Grip silicona mando — licencia",
    "Sony Grip silicona mando — pack 2",
    "Sony Cable HDMI 8K — PS5",
    "Sony Cable HDMI 8K — Xbox Series",
    "Sony Cable HDMI 8K — Switch 2",
    "Sony Cable HDMI 8K — PC",
    "Sony Cable HDMI 8K — Steam Deck",
    "Sony Cable HDMI 8K — negro",
    "Sony Cable HDMI 8K — licencia",
    "Sony Cable HDMI 8K — pack 2",
    "Sony Base carga oficial — PS5",
    "Sony Base carga oficial — Xbox Series",
    "Sony Base carga oficial — Switch 2",
    "Sony Base carga oficial — PC",
    "Sony Base carga oficial — Steam Deck",
    "Sony Base carga oficial — negro",
    "Sony Base carga oficial — licencia",
    "Sony Base carga oficial — pack 2",
    "Sony Funda transporte — PS5",
    "Sony Funda transporte — Xbox Series",
    "Sony Funda transporte — Switch 2",
    "Sony Funda transporte — PC",
    "Sony Funda transporte — Steam Deck",
    "Sony Funda transporte — negro",
    "Sony Funda transporte — licencia",
    "Sony Funda transporte — pack 2",
    "Sony Thumbstick caps — PS5",
    "Sony Thumbstick caps — Xbox Series",
    "Sony Thumbstick caps — Switch 2",
    "Sony Thumbstick caps — PC",
    "Sony Thumbstick caps — Steam Deck",
    "Sony Thumbstick caps — negro",
    "Sony Thumbstick caps — licencia",
    "Sony Thumbstick caps — pack 2",
    "Sony Skin anti-rayado — PS5",
    "Sony Skin anti-rayado — Xbox Series"
  ],
  "tv-audio": [
    "LG Barra sonido montaje — 55-65",
    "LG Barra sonido montaje — 65-75",
    "LG Barra sonido montaje — eARC",
    "LG Barra sonido montaje — Dolby Atmos",
    "LG Barra sonido montaje — 4K120",
    "LG Barra sonido montaje — 2m",
    "LG Barra sonido montaje — 3m",
    "LG Barra sonido montaje — pack",
    "LG Cable óptico premium — 55-65",
    "LG Cable óptico premium — 65-75",
    "LG Cable óptico premium — eARC",
    "LG Cable óptico premium — Dolby Atmos",
    "LG Cable óptico premium — 4K120",
    "LG Cable óptico premium — 2m",
    "LG Cable óptico premium — 3m",
    "LG Cable óptico premium — pack",
    "LG Adaptador eARC — 55-65",
    "LG Adaptador eARC — 65-75",
    "LG Adaptador eARC — eARC",
    "LG Adaptador eARC — Dolby Atmos",
    "LG Adaptador eARC — 4K120",
    "LG Adaptador eARC — 2m",
    "LG Adaptador eARC — 3m",
    "LG Adaptador eARC — pack",
    "LG Soporte barra — 55-65",
    "LG Soporte barra — 65-75",
    "LG Soporte barra — eARC",
    "LG Soporte barra — Dolby Atmos",
    "LG Soporte barra — 4K120",
    "LG Soporte barra — 2m",
    "LG Soporte barra — 3m",
    "LG Soporte barra — pack",
    "LG Antena TDT amplificada — 55-65",
    "LG Antena TDT amplificada — 65-75",
    "LG Antena TDT amplificada — eARC",
    "LG Antena TDT amplificada — Dolby Atmos",
    "LG Antena TDT amplificada — 4K120",
    "LG Antena TDT amplificada — 2m",
    "LG Antena TDT amplificada — 3m",
    "LG Antena TDT amplificada — pack",
    "LG Regleta 6 tomas — 55-65",
    "LG Regleta 6 tomas — 65-75"
  ],
  "foto-video": [
    "Canon Tarjeta SD V60 256 — 67mm",
    "Canon Tarjeta SD V60 256 — 77mm",
    "Canon Tarjeta SD V60 256 — 82mm",
    "Canon Tarjeta SD V60 256 — CFexpress",
    "Canon Tarjeta SD V60 256 — SDXC",
    "Canon Tarjeta SD V60 256 — profesional",
    "Canon Tarjeta SD V60 256 — viaje",
    "Canon Tarjeta SD V60 256 — 4K",
    "Canon Reader USB-C dual — 67mm",
    "Canon Reader USB-C dual — 77mm",
    "Canon Reader USB-C dual — 82mm",
    "Canon Reader USB-C dual — CFexpress",
    "Canon Reader USB-C dual — SDXC",
    "Canon Reader USB-C dual — profesional",
    "Canon Reader USB-C dual — viaje",
    "Canon Reader USB-C dual — 4K",
    "Canon Correa crossbody — 67mm",
    "Canon Correa crossbody — 77mm",
    "Canon Correa crossbody — 82mm",
    "Canon Correa crossbody — CFexpress",
    "Canon Correa crossbody — SDXC",
    "Canon Correa crossbody — profesional",
    "Canon Correa crossbody — viaje",
    "Canon Correa crossbody — 4K",
    "Canon Funda lluvia — 67mm",
    "Canon Funda lluvia — 77mm",
    "Canon Funda lluvia — 82mm",
    "Canon Funda lluvia — CFexpress",
    "Canon Funda lluvia — SDXC",
    "Canon Funda lluvia — profesional",
    "Canon Funda lluvia — viaje",
    "Canon Funda lluvia — 4K",
    "Canon Filtro UV 67mm — 67mm",
    "Canon Filtro UV 67mm — 77mm",
    "Canon Filtro UV 67mm — 82mm",
    "Canon Filtro UV 67mm — CFexpress",
    "Canon Filtro UV 67mm — SDXC",
    "Canon Filtro UV 67mm — profesional",
    "Canon Filtro UV 67mm — viaje",
    "Canon Filtro UV 67mm — 4K",
    "Canon Kit limpieza lente — 67mm",
    "Canon Kit limpieza lente — 77mm"
  ],
  "smart-home": [
    "Aqara Sensor humedad — Matter",
    "Aqara Sensor humedad — Thread",
    "Aqara Sensor humedad — Zigbee",
    "Aqara Sensor humedad — WiFi",
    "Aqara Sensor humedad — exterior",
    "Aqara Sensor humedad — interior",
    "Aqara Sensor humedad — pack 2",
    "Aqara Sensor humedad — blanco",
    "Aqara Bombilla E27 Matter — Matter",
    "Aqara Bombilla E27 Matter — Thread",
    "Aqara Bombilla E27 Matter — Zigbee",
    "Aqara Bombilla E27 Matter — WiFi",
    "Aqara Bombilla E27 Matter — exterior",
    "Aqara Bombilla E27 Matter — interior",
    "Aqara Bombilla E27 Matter — pack 2",
    "Aqara Bombilla E27 Matter — blanco",
    "Aqara Enchufe exterior IP44 — Matter",
    "Aqara Enchufe exterior IP44 — Thread",
    "Aqara Enchufe exterior IP44 — Zigbee",
    "Aqara Enchufe exterior IP44 — WiFi",
    "Aqara Enchufe exterior IP44 — exterior",
    "Aqara Enchufe exterior IP44 — interior",
    "Aqara Enchufe exterior IP44 — pack 2",
    "Aqara Enchufe exterior IP44 — blanco",
    "Aqara Timbre vídeo — Matter",
    "Aqara Timbre vídeo — Thread",
    "Aqara Timbre vídeo — Zigbee",
    "Aqara Timbre vídeo — WiFi",
    "Aqara Timbre vídeo — exterior",
    "Aqara Timbre vídeo — interior",
    "Aqara Timbre vídeo — pack 2",
    "Aqara Timbre vídeo — blanco",
    "Aqara Hub Zigbee — Matter",
    "Aqara Hub Zigbee — Thread",
    "Aqara Hub Zigbee — Zigbee",
    "Aqara Hub Zigbee — WiFi",
    "Aqara Hub Zigbee — exterior",
    "Aqara Hub Zigbee — interior",
    "Aqara Hub Zigbee — pack 2",
    "Aqara Hub Zigbee — blanco",
    "Aqara Sensor CO2 — Matter",
    "Aqara Sensor CO2 — Thread"
  ],
  "hogar-cocina": [
    "Le Creuset Set cuchillos chef — inox",
    "Le Creuset Set cuchillos chef — antiadherente",
    "Le Creuset Set cuchillos chef — inducción",
    "Le Creuset Set cuchillos chef — set 3",
    "Le Creuset Set cuchillos chef — set 5",
    "Le Creuset Set cuchillos chef — regalo",
    "Le Creuset Set cuchillos chef — chef",
    "Le Creuset Set cuchillos chef — hogar",
    "Le Creuset Tabla cortar bambú — inox",
    "Le Creuset Tabla cortar bambú — antiadherente",
    "Le Creuset Tabla cortar bambú — inducción",
    "Le Creuset Tabla cortar bambú — set 3",
    "Le Creuset Tabla cortar bambú — set 5",
    "Le Creuset Tabla cortar bambú — regalo",
    "Le Creuset Tabla cortar bambú — chef",
    "Le Creuset Tabla cortar bambú — hogar",
    "Le Creuset Molde horno silicona — inox",
    "Le Creuset Molde horno silicona — antiadherente",
    "Le Creuset Molde horno silicona — inducción",
    "Le Creuset Molde horno silicona — set 3",
    "Le Creuset Molde horno silicona — set 5",
    "Le Creuset Molde horno silicona — regalo",
    "Le Creuset Molde horno silicona — chef",
    "Le Creuset Molde horno silicona — hogar",
    "Le Creuset Termómetro horno — inox",
    "Le Creuset Termómetro horno — antiadherente",
    "Le Creuset Termómetro horno — inducción",
    "Le Creuset Termómetro horno — set 3",
    "Le Creuset Termómetro horno — set 5",
    "Le Creuset Termómetro horno — regalo",
    "Le Creuset Termómetro horno — chef",
    "Le Creuset Termómetro horno — hogar",
    "Le Creuset Batidor varillas — inox",
    "Le Creuset Batidor varillas — antiadherente",
    "Le Creuset Batidor varillas — inducción",
    "Le Creuset Batidor varillas — set 3",
    "Le Creuset Batidor varillas — set 5",
    "Le Creuset Batidor varillas — regalo",
    "Le Creuset Batidor varillas — chef",
    "Le Creuset Batidor varillas — hogar",
    "Le Creuset Escurridor pasta — inox",
    "Le Creuset Escurridor pasta — antiadherente"
  ],
  "pequeno-electro": [
    "DeLonghi Filtro carbón cafetera — original",
    "DeLonghi Filtro carbón cafetera — compatible",
    "DeLonghi Filtro carbón cafetera — pack 4",
    "DeLonghi Filtro carbón cafetera — serie 5000",
    "DeLonghi Filtro carbón cafetera — XL",
    "DeLonghi Filtro carbón cafetera — HEPA",
    "DeLonghi Filtro carbón cafetera — recambio",
    "DeLonghi Filtro carbón cafetera — OFERTA",
    "DeLonghi Recambio cepillo — original",
    "DeLonghi Recambio cepillo — compatible",
    "DeLonghi Recambio cepillo — pack 4",
    "DeLonghi Recambio cepillo — serie 5000",
    "DeLonghi Recambio cepillo — XL",
    "DeLonghi Recambio cepillo — HEPA",
    "DeLonghi Recambio cepillo — recambio",
    "DeLonghi Recambio cepillo — OFERTA",
    "DeLonghi Depósito agua — original",
    "DeLonghi Depósito agua — compatible",
    "DeLonghi Depósito agua — pack 4",
    "DeLonghi Depósito agua — serie 5000",
    "DeLonghi Depósito agua — XL",
    "DeLonghi Depósito agua — HEPA",
    "DeLonghi Depósito agua — recambio",
    "DeLonghi Depósito agua — OFERTA",
    "DeLonghi Base plancha — original",
    "DeLonghi Base plancha — compatible",
    "DeLonghi Base plancha — pack 4",
    "DeLonghi Base plancha — serie 5000",
    "DeLonghi Base plancha — XL",
    "DeLonghi Base plancha — HEPA",
    "DeLonghi Base plancha — recambio",
    "DeLonghi Base plancha — OFERTA",
    "DeLonghi Bolsa aspirador — original",
    "DeLonghi Bolsa aspirador — compatible",
    "DeLonghi Bolsa aspirador — pack 4",
    "DeLonghi Bolsa aspirador — serie 5000",
    "DeLonghi Bolsa aspirador — XL",
    "DeLonghi Bolsa aspirador — HEPA",
    "DeLonghi Bolsa aspirador — recambio",
    "DeLonghi Bolsa aspirador — OFERTA",
    "DeLonghi Mopa repuesto — original",
    "DeLonghi Mopa repuesto — compatible"
  ],
  "hogar": [
    "IKEA Percha madera 10 uds — blanco",
    "IKEA Percha madera 10 uds — gris",
    "IKEA Percha madera 10 uds — beige",
    "IKEA Percha madera 10 uds — 40cm",
    "IKEA Percha madera 10 uds — 60cm",
    "IKEA Percha madera 10 uds — bambú",
    "IKEA Percha madera 10 uds — reciclado",
    "IKEA Percha madera 10 uds — pack",
    "IKEA Caja organización — blanco",
    "IKEA Caja organización — gris",
    "IKEA Caja organización — beige",
    "IKEA Caja organización — 40cm",
    "IKEA Caja organización — 60cm",
    "IKEA Caja organización — bambú",
    "IKEA Caja organización — reciclado",
    "IKEA Caja organización — pack",
    "IKEA Cortina ducha — blanco",
    "IKEA Cortina ducha — gris",
    "IKEA Cortina ducha — beige",
    "IKEA Cortina ducha — 40cm",
    "IKEA Cortina ducha — 60cm",
    "IKEA Cortina ducha — bambú",
    "IKEA Cortina ducha — reciclado",
    "IKEA Cortina ducha — pack",
    "IKEA Alfombrilla baño — blanco",
    "IKEA Alfombrilla baño — gris",
    "IKEA Alfombrilla baño — beige",
    "IKEA Alfombrilla baño — 40cm",
    "IKEA Alfombrilla baño — 60cm",
    "IKEA Alfombrilla baño — bambú",
    "IKEA Alfombrilla baño — reciclado",
    "IKEA Alfombrilla baño — pack",
    "IKEA Dispensador jabón — blanco",
    "IKEA Dispensador jabón — gris",
    "IKEA Dispensador jabón — beige",
    "IKEA Dispensador jabón — 40cm",
    "IKEA Dispensador jabón — 60cm",
    "IKEA Dispensador jabón — bambú",
    "IKEA Dispensador jabón — reciclado",
    "IKEA Dispensador jabón — pack",
    "IKEA Escobilla WC — blanco",
    "IKEA Escobilla WC — gris"
  ],
  "aspiracion-limpieza": [
    "Dyson Filtro postmotor — original",
    "Dyson Filtro postmotor — compatible",
    "Dyson Filtro postmotor — pack 2",
    "Dyson Filtro postmotor — HEPA",
    "Dyson Filtro postmotor — mascotas",
    "Dyson Filtro postmotor — lavable",
    "Dyson Filtro postmotor — XL",
    "Dyson Filtro postmotor — recambio",
    "Dyson Cepillo turbo — original",
    "Dyson Cepillo turbo — compatible",
    "Dyson Cepillo turbo — pack 2",
    "Dyson Cepillo turbo — HEPA",
    "Dyson Cepillo turbo — mascotas",
    "Dyson Cepillo turbo — lavable",
    "Dyson Cepillo turbo — XL",
    "Dyson Cepillo turbo — recambio",
    "Dyson Mopa repuesto — original",
    "Dyson Mopa repuesto — compatible",
    "Dyson Mopa repuesto — pack 2",
    "Dyson Mopa repuesto — HEPA",
    "Dyson Mopa repuesto — mascotas",
    "Dyson Mopa repuesto — lavable",
    "Dyson Mopa repuesto — XL",
    "Dyson Mopa repuesto — recambio",
    "Dyson Bolsa polvo — original",
    "Dyson Bolsa polvo — compatible",
    "Dyson Bolsa polvo — pack 2",
    "Dyson Bolsa polvo — HEPA",
    "Dyson Bolsa polvo — mascotas",
    "Dyson Bolsa polvo — lavable",
    "Dyson Bolsa polvo — XL",
    "Dyson Bolsa polvo — recambio",
    "Dyson Detergente suelos — original",
    "Dyson Detergente suelos — compatible",
    "Dyson Detergente suelos — pack 2",
    "Dyson Detergente suelos — HEPA",
    "Dyson Detergente suelos — mascotas",
    "Dyson Detergente suelos — lavable",
    "Dyson Detergente suelos — XL",
    "Dyson Detergente suelos — recambio",
    "Dyson Recambio rodillo — original",
    "Dyson Recambio rodillo — compatible"
  ],
  "climatizacion": [
    "Daikin Filtro purificador — HEPA",
    "Daikin Filtro purificador — 9000 BTU",
    "Daikin Filtro purificador — 12000 BTU",
    "Daikin Filtro purificador — WiFi",
    "Daikin Filtro purificador — universal",
    "Daikin Filtro purificador — silencioso",
    "Daikin Filtro purificador — pack 2",
    "Daikin Filtro purificador — carbón",
    "Daikin Mando universal AC — HEPA",
    "Daikin Mando universal AC — 9000 BTU",
    "Daikin Mando universal AC — 12000 BTU",
    "Daikin Mando universal AC — WiFi",
    "Daikin Mando universal AC — universal",
    "Daikin Mando universal AC — silencioso",
    "Daikin Mando universal AC — pack 2",
    "Daikin Mando universal AC — carbón",
    "Daikin Kit ventana — HEPA",
    "Daikin Kit ventana — 9000 BTU",
    "Daikin Kit ventana — 12000 BTU",
    "Daikin Kit ventana — WiFi",
    "Daikin Kit ventana — universal",
    "Daikin Kit ventana — silencioso",
    "Daikin Kit ventana — pack 2",
    "Daikin Kit ventana — carbón",
    "Daikin Difusor aromas — HEPA",
    "Daikin Difusor aromas — 9000 BTU",
    "Daikin Difusor aromas — 12000 BTU",
    "Daikin Difusor aromas — WiFi",
    "Daikin Difusor aromas — universal",
    "Daikin Difusor aromas — silencioso",
    "Daikin Difusor aromas — pack 2",
    "Daikin Difusor aromas — carbón",
    "Daikin Sensor temperatura — HEPA",
    "Daikin Sensor temperatura — 9000 BTU",
    "Daikin Sensor temperatura — 12000 BTU",
    "Daikin Sensor temperatura — WiFi",
    "Daikin Sensor temperatura — universal",
    "Daikin Sensor temperatura — silencioso",
    "Daikin Sensor temperatura — pack 2",
    "Daikin Sensor temperatura — carbón",
    "Daikin Timer enchufe — HEPA",
    "Daikin Timer enchufe — 9000 BTU"
  ],
  "belleza": [
    "L'Oréal Set brochas viaje — vegano",
    "L'Oréal Set brochas viaje — regalo",
    "L'Oréal Set brochas viaje — travel",
    "L'Oréal Set brochas viaje — SPF 50",
    "L'Oréal Set brochas viaje — piel sensible",
    "L'Oréal Set brochas viaje — profesional",
    "L'Oréal Set brochas viaje — pack",
    "L'Oréal Set brochas viaje — edición 2025",
    "L'Oréal Esponja maquillaje — vegano",
    "L'Oréal Esponja maquillaje — regalo",
    "L'Oréal Esponja maquillaje — travel",
    "L'Oréal Esponja maquillaje — SPF 50",
    "L'Oréal Esponja maquillaje — piel sensible",
    "L'Oréal Esponja maquillaje — profesional",
    "L'Oréal Esponja maquillaje — pack",
    "L'Oréal Esponja maquillaje — edición 2025",
    "L'Oréal Neceser cosmética — vegano",
    "L'Oréal Neceser cosmética — regalo",
    "L'Oréal Neceser cosmética — travel",
    "L'Oréal Neceser cosmética — SPF 50",
    "L'Oréal Neceser cosmética — piel sensible",
    "L'Oréal Neceser cosmética — profesional",
    "L'Oréal Neceser cosmética — pack",
    "L'Oréal Neceser cosmética — edición 2025",
    "L'Oréal Espejo LED — vegano",
    "L'Oréal Espejo LED — regalo",
    "L'Oréal Espejo LED — travel",
    "L'Oréal Espejo LED — SPF 50",
    "L'Oréal Espejo LED — piel sensible",
    "L'Oréal Espejo LED — profesional",
    "L'Oréal Espejo LED — pack",
    "L'Oréal Espejo LED — edición 2025",
    "L'Oréal Organizador labiales — vegano",
    "L'Oréal Organizador labiales — regalo",
    "L'Oréal Organizador labiales — travel",
    "L'Oréal Organizador labiales — SPF 50",
    "L'Oréal Organizador labiales — piel sensible",
    "L'Oréal Organizador labiales — profesional",
    "L'Oréal Organizador labiales — pack",
    "L'Oréal Organizador labiales — edición 2025",
    "L'Oréal Cap secado pelo — vegano",
    "L'Oréal Cap secado pelo — regalo"
  ],
  "salud-deporte": [
    "Withings Correa reloj — M",
    "Withings Correa reloj — L",
    "Withings Correa reloj — Bluetooth",
    "Withings Correa reloj — recargable",
    "Withings Correa reloj — clínico",
    "Withings Correa reloj — deportivo",
    "Withings Correa reloj — pack 2",
    "Withings Correa reloj — unisex",
    "Withings Protector pantalla — M",
    "Withings Protector pantalla — L",
    "Withings Protector pantalla — Bluetooth",
    "Withings Protector pantalla — recargable",
    "Withings Protector pantalla — clínico",
    "Withings Protector pantalla — deportivo",
    "Withings Protector pantalla — pack 2",
    "Withings Protector pantalla — unisex",
    "Withings Electrodos TENS — M",
    "Withings Electrodos TENS — L",
    "Withings Electrodos TENS — Bluetooth",
    "Withings Electrodos TENS — recargable",
    "Withings Electrodos TENS — clínico",
    "Withings Electrodos TENS — deportivo",
    "Withings Electrodos TENS — pack 2",
    "Withings Electrodos TENS — unisex",
    "Withings Banda FC pecho — M",
    "Withings Banda FC pecho — L",
    "Withings Banda FC pecho — Bluetooth",
    "Withings Banda FC pecho — recargable",
    "Withings Banda FC pecho — clínico",
    "Withings Banda FC pecho — deportivo",
    "Withings Banda FC pecho — pack 2",
    "Withings Banda FC pecho — unisex",
    "Withings Rodillo foam — M",
    "Withings Rodillo foam — L",
    "Withings Rodillo foam — Bluetooth",
    "Withings Rodillo foam — recargable",
    "Withings Rodillo foam — clínico",
    "Withings Rodillo foam — deportivo",
    "Withings Rodillo foam — pack 2",
    "Withings Rodillo foam — unisex",
    "Withings Banda elasticidad — M",
    "Withings Banda elasticidad — L"
  ],
  "deportes": [
    "Nike Calcetines running — talla M",
    "Nike Calcetines running — talla L",
    "Nike Calcetines running — running",
    "Nike Calcetines running — trail",
    "Nike Calcetines running — negro",
    "Nike Calcetines running — reflectante",
    "Nike Calcetines running — pack 3",
    "Nike Calcetines running — unisex",
    "Nike Cinturón hidratación — talla M",
    "Nike Cinturón hidratación — talla L",
    "Nike Cinturón hidratación — running",
    "Nike Cinturón hidratación — trail",
    "Nike Cinturón hidratación — negro",
    "Nike Cinturón hidratación — reflectante",
    "Nike Cinturón hidratación — pack 3",
    "Nike Cinturón hidratación — unisex",
    "Nike Guantes gimnasio — talla M",
    "Nike Guantes gimnasio — talla L",
    "Nike Guantes gimnasio — running",
    "Nike Guantes gimnasio — trail",
    "Nike Guantes gimnasio — negro",
    "Nike Guantes gimnasio — reflectante",
    "Nike Guantes gimnasio — pack 3",
    "Nike Guantes gimnasio — unisex",
    "Nike Plantillas running — talla M",
    "Nike Plantillas running — talla L",
    "Nike Plantillas running — running",
    "Nike Plantillas running — trail",
    "Nike Plantillas running — negro",
    "Nike Plantillas running — reflectante",
    "Nike Plantillas running — pack 3",
    "Nike Plantillas running — unisex",
    "Nike Botella 750ml — talla M",
    "Nike Botella 750ml — talla L",
    "Nike Botella 750ml — running",
    "Nike Botella 750ml — trail",
    "Nike Botella 750ml — negro",
    "Nike Botella 750ml — reflectante",
    "Nike Botella 750ml — pack 3",
    "Nike Botella 750ml — unisex",
    "Nike Mochila trail — talla M",
    "Nike Mochila trail — talla L"
  ],
  "ropa": [
    "Zara Calcetines algodón — talla M",
    "Zara Calcetines algodón — talla L",
    "Zara Calcetines algodón — negro",
    "Zara Calcetines algodón — beige",
    "Zara Calcetines algodón — unisex",
    "Zara Calcetines algodón — algodón orgánico",
    "Zara Calcetines algodón — pack",
    "Zara Calcetines algodón — AW25",
    "Zara Cinturón piel — talla M",
    "Zara Cinturón piel — talla L",
    "Zara Cinturón piel — negro",
    "Zara Cinturón piel — beige",
    "Zara Cinturón piel — unisex",
    "Zara Cinturón piel — algodón orgánico",
    "Zara Cinturón piel — pack",
    "Zara Cinturón piel — AW25",
    "Zara Guantes lana — talla M",
    "Zara Guantes lana — talla L",
    "Zara Guantes lana — negro",
    "Zara Guantes lana — beige",
    "Zara Guantes lana — unisex",
    "Zara Guantes lana — algodón orgánico",
    "Zara Guantes lana — pack",
    "Zara Guantes lana — AW25",
    "Zara Gorro punto — talla M",
    "Zara Gorro punto — talla L",
    "Zara Gorro punto — negro",
    "Zara Gorro punto — beige",
    "Zara Gorro punto — unisex",
    "Zara Gorro punto — algodón orgánico",
    "Zara Gorro punto — pack",
    "Zara Gorro punto — AW25",
    "Zara Bufanda — talla M",
    "Zara Bufanda — talla L",
    "Zara Bufanda — negro",
    "Zara Bufanda — beige",
    "Zara Bufanda — unisex",
    "Zara Bufanda — algodón orgánico",
    "Zara Bufanda — pack",
    "Zara Bufanda — AW25",
    "Zara Perchas terciopelo — talla M",
    "Zara Perchas terciopelo — talla L"
  ],
  "relojes-accesorios": [
    "Casio Correa acero — 18mm",
    "Casio Correa acero — 20mm",
    "Casio Correa acero — 22mm",
    "Casio Correa acero — negro",
    "Casio Correa acero — cuero",
    "Casio Correa acero — acero",
    "Casio Correa acero — quick release",
    "Casio Correa acero — pack",
    "Casio Correa NATO — 18mm",
    "Casio Correa NATO — 20mm",
    "Casio Correa NATO — 22mm",
    "Casio Correa NATO — negro",
    "Casio Correa NATO — cuero",
    "Casio Correa NATO — acero",
    "Casio Correa NATO — quick release",
    "Casio Correa NATO — pack",
    "Casio Estuche reloj — 18mm",
    "Casio Estuche reloj — 20mm",
    "Casio Estuche reloj — 22mm",
    "Casio Estuche reloj — negro",
    "Casio Estuche reloj — cuero",
    "Casio Estuche reloj — acero",
    "Casio Estuche reloj — quick release",
    "Casio Estuche reloj — pack",
    "Casio Kit herramientas — 18mm",
    "Casio Kit herramientas — 20mm",
    "Casio Kit herramientas — 22mm",
    "Casio Kit herramientas — negro",
    "Casio Kit herramientas — cuero",
    "Casio Kit herramientas — acero",
    "Casio Kit herramientas — quick release",
    "Casio Kit herramientas — pack",
    "Casio Protector pantalla — 18mm",
    "Casio Protector pantalla — 20mm",
    "Casio Protector pantalla — 22mm",
    "Casio Protector pantalla — negro",
    "Casio Protector pantalla — cuero",
    "Casio Protector pantalla — acero",
    "Casio Protector pantalla — quick release",
    "Casio Protector pantalla — pack",
    "Casio Cargador smartwatch — 18mm",
    "Casio Cargador smartwatch — 20mm"
  ],
  "maletas-viaje": [
    "Samsonite Packing cubes 5 — cabina",
    "Samsonite Packing cubes 5 — S",
    "Samsonite Packing cubes 5 — M",
    "Samsonite Packing cubes 5 — L",
    "Samsonite Packing cubes 5 — antirrobo",
    "Samsonite Packing cubes 5 — negro",
    "Samsonite Packing cubes 5 — pack viaje",
    "Samsonite Packing cubes 5 — reciclado",
    "Samsonite Candado TSA — cabina",
    "Samsonite Candado TSA — S",
    "Samsonite Candado TSA — M",
    "Samsonite Candado TSA — L",
    "Samsonite Candado TSA — antirrobo",
    "Samsonite Candado TSA — negro",
    "Samsonite Candado TSA — pack viaje",
    "Samsonite Candado TSA — reciclado",
    "Samsonite Etiqueta equipaje — cabina",
    "Samsonite Etiqueta equipaje — S",
    "Samsonite Etiqueta equipaje — M",
    "Samsonite Etiqueta equipaje — L",
    "Samsonite Etiqueta equipaje — antirrobo",
    "Samsonite Etiqueta equipaje — negro",
    "Samsonite Etiqueta equipaje — pack viaje",
    "Samsonite Etiqueta equipaje — reciclado",
    "Samsonite Almohada cervical — cabina",
    "Samsonite Almohada cervical — S",
    "Samsonite Almohada cervical — M",
    "Samsonite Almohada cervical — L",
    "Samsonite Almohada cervical — antirrobo",
    "Samsonite Almohada cervical — negro",
    "Samsonite Almohada cervical — pack viaje",
    "Samsonite Almohada cervical — reciclado",
    "Samsonite Adaptador universal — cabina",
    "Samsonite Adaptador universal — S",
    "Samsonite Adaptador universal — M",
    "Samsonite Adaptador universal — L",
    "Samsonite Adaptador universal — antirrobo",
    "Samsonite Adaptador universal — negro",
    "Samsonite Adaptador universal — pack viaje",
    "Samsonite Adaptador universal — reciclado",
    "Samsonite Neceser colgante — cabina",
    "Samsonite Neceser colgante — S"
  ],
  "piscina-playa": [
    "Intex Cloro piscina — piscina",
    "Intex Cloro piscina — playa",
    "Intex Cloro piscina — niño",
    "Intex Cloro piscina — adulto",
    "Intex Cloro piscina — UV50",
    "Intex Cloro piscina — pack",
    "Intex Cloro piscina — recambio",
    "Intex Cloro piscina — verano 2025",
    "Intex Filtro cartucho — piscina",
    "Intex Filtro cartucho — playa",
    "Intex Filtro cartucho — niño",
    "Intex Filtro cartucho — adulto",
    "Intex Filtro cartucho — UV50",
    "Intex Filtro cartucho — pack",
    "Intex Filtro cartucho — recambio",
    "Intex Filtro cartucho — verano 2025",
    "Intex Toldo playa — piscina",
    "Intex Toldo playa — playa",
    "Intex Toldo playa — niño",
    "Intex Toldo playa — adulto",
    "Intex Toldo playa — UV50",
    "Intex Toldo playa — pack",
    "Intex Toldo playa — recambio",
    "Intex Toldo playa — verano 2025",
    "Intex Gafas snorkel — piscina",
    "Intex Gafas snorkel — playa",
    "Intex Gafas snorkel — niño",
    "Intex Gafas snorkel — adulto",
    "Intex Gafas snorkel — UV50",
    "Intex Gafas snorkel — pack",
    "Intex Gafas snorkel — recambio",
    "Intex Gafas snorkel — verano 2025",
    "Intex Chanclas agua — piscina",
    "Intex Chanclas agua — playa",
    "Intex Chanclas agua — niño",
    "Intex Chanclas agua — adulto",
    "Intex Chanclas agua — UV50",
    "Intex Chanclas agua — pack",
    "Intex Chanclas agua — recambio",
    "Intex Chanclas agua — verano 2025",
    "Intex Bolsa estanca — piscina",
    "Intex Bolsa estanca — playa"
  ],
  "jardin": [
    "Gardena Manguera 20m — 15m",
    "Gardena Manguera 20m — 30m",
    "Gardena Manguera 20m — 18V",
    "Gardena Manguera 20m — orgánico",
    "Gardena Manguera 20m — pack",
    "Gardena Manguera 20m — eco",
    "Gardena Manguera 20m — adulto",
    "Gardena Manguera 20m — profesional",
    "Gardena Pistola riego — 15m",
    "Gardena Pistola riego — 30m",
    "Gardena Pistola riego — 18V",
    "Gardena Pistola riego — orgánico",
    "Gardena Pistola riego — pack",
    "Gardena Pistola riego — eco",
    "Gardena Pistola riego — adulto",
    "Gardena Pistola riego — profesional",
    "Gardena Guantes jardín — 15m",
    "Gardena Guantes jardín — 30m",
    "Gardena Guantes jardín — 18V",
    "Gardena Guantes jardín — orgánico",
    "Gardena Guantes jardín — pack",
    "Gardena Guantes jardín — eco",
    "Gardena Guantes jardín — adulto",
    "Gardena Guantes jardín — profesional",
    "Gardena Tijeras poda — 15m",
    "Gardena Tijeras poda — 30m",
    "Gardena Tijeras poda — 18V",
    "Gardena Tijeras poda — orgánico",
    "Gardena Tijeras poda — pack",
    "Gardena Tijeras poda — eco",
    "Gardena Tijeras poda — adulto",
    "Gardena Tijeras poda — profesional",
    "Gardena Semillas césped — 15m",
    "Gardena Semillas césped — 30m",
    "Gardena Semillas césped — 18V",
    "Gardena Semillas césped — orgánico",
    "Gardena Semillas césped — pack",
    "Gardena Semillas césped — eco",
    "Gardena Semillas césped — adulto",
    "Gardena Semillas césped — profesional",
    "Gardena Abono universal — 15m",
    "Gardena Abono universal — 30m"
  ],
  "bricolaje": [
    "Bosch Broca set 15 — HSS",
    "Bosch Broca set 15 — 18V",
    "Bosch Broca set 15 — profesional",
    "Bosch Broca set 15 — bricolaje",
    "Bosch Broca set 15 — pack",
    "Bosch Broca set 15 — 220V",
    "Bosch Broca set 15 — negro",
    "Bosch Broca set 15 — amarillo",
    "Bosch Disco corte 10 — HSS",
    "Bosch Disco corte 10 — 18V",
    "Bosch Disco corte 10 — profesional",
    "Bosch Disco corte 10 — bricolaje",
    "Bosch Disco corte 10 — pack",
    "Bosch Disco corte 10 — 220V",
    "Bosch Disco corte 10 — negro",
    "Bosch Disco corte 10 — amarillo",
    "Bosch Cinta métrica — HSS",
    "Bosch Cinta métrica — 18V",
    "Bosch Cinta métrica — profesional",
    "Bosch Cinta métrica — bricolaje",
    "Bosch Cinta métrica — pack",
    "Bosch Cinta métrica — 220V",
    "Bosch Cinta métrica — negro",
    "Bosch Cinta métrica — amarillo",
    "Bosch Nivel láser — HSS",
    "Bosch Nivel láser — 18V",
    "Bosch Nivel láser — profesional",
    "Bosch Nivel láser — bricolaje",
    "Bosch Nivel láser — pack",
    "Bosch Nivel láser — 220V",
    "Bosch Nivel láser — negro",
    "Bosch Nivel láser — amarillo",
    "Bosch Guantes trabajo — HSS",
    "Bosch Guantes trabajo — 18V",
    "Bosch Guantes trabajo — profesional",
    "Bosch Guantes trabajo — bricolaje",
    "Bosch Guantes trabajo — pack",
    "Bosch Guantes trabajo — 220V",
    "Bosch Guantes trabajo — negro",
    "Bosch Guantes trabajo — amarillo",
    "Bosch Gafas protección — HSS",
    "Bosch Gafas protección — 18V"
  ],
  "oficina": [
    "Fellowes Grapas 5000 — A4",
    "Fellowes Grapas 5000 — A5",
    "Fellowes Grapas 5000 — negro",
    "Fellowes Grapas 5000 — reciclado",
    "Fellowes Grapas 5000 — pack 5",
    "Fellowes Grapas 5000 — oficina",
    "Fellowes Grapas 5000 — colores",
    "Fellowes Grapas 5000 — profesional",
    "Fellowes Fundas plastificar — A4",
    "Fellowes Fundas plastificar — A5",
    "Fellowes Fundas plastificar — negro",
    "Fellowes Fundas plastificar — reciclado",
    "Fellowes Fundas plastificar — pack 5",
    "Fellowes Fundas plastificar — oficina",
    "Fellowes Fundas plastificar — colores",
    "Fellowes Fundas plastificar — profesional",
    "Fellowes Organizador escritorio — A4",
    "Fellowes Organizador escritorio — A5",
    "Fellowes Organizador escritorio — negro",
    "Fellowes Organizador escritorio — reciclado",
    "Fellowes Organizador escritorio — pack 5",
    "Fellowes Organizador escritorio — oficina",
    "Fellowes Organizador escritorio — colores",
    "Fellowes Organizador escritorio — profesional",
    "Fellowes Reposapiés — A4",
    "Fellowes Reposapiés — A5",
    "Fellowes Reposapiés — negro",
    "Fellowes Reposapiés — reciclado",
    "Fellowes Reposapiés — pack 5",
    "Fellowes Reposapiés — oficina",
    "Fellowes Reposapiés — colores",
    "Fellowes Reposapiés — profesional",
    "Fellowes Rotuladores 12 — A4",
    "Fellowes Rotuladores 12 — A5",
    "Fellowes Rotuladores 12 — negro",
    "Fellowes Rotuladores 12 — reciclado",
    "Fellowes Rotuladores 12 — pack 5",
    "Fellowes Rotuladores 12 — oficina",
    "Fellowes Rotuladores 12 — colores",
    "Fellowes Rotuladores 12 — profesional",
    "Fellowes Archivador palanca — A4",
    "Fellowes Archivador palanca — A5"
  ],
  "libros": [
    "Planeta Marcapáginas set — regalo",
    "Planeta Marcapáginas set — español",
    "Planeta Marcapáginas set — A5",
    "Planeta Marcapáginas set — bolsillo",
    "Planeta Marcapáginas set — tapa dura",
    "Planeta Marcapáginas set — audiolibro",
    "Planeta Marcapáginas set — pack 3",
    "Planeta Marcapáginas set — 2025",
    "Planeta Luz lectura — regalo",
    "Planeta Luz lectura — español",
    "Planeta Luz lectura — A5",
    "Planeta Luz lectura — bolsillo",
    "Planeta Luz lectura — tapa dura",
    "Planeta Luz lectura — audiolibro",
    "Planeta Luz lectura — pack 3",
    "Planeta Luz lectura — 2025",
    "Planeta Soporte libro — regalo",
    "Planeta Soporte libro — español",
    "Planeta Soporte libro — A5",
    "Planeta Soporte libro — bolsillo",
    "Planeta Soporte libro — tapa dura",
    "Planeta Soporte libro — audiolibro",
    "Planeta Soporte libro — pack 3",
    "Planeta Soporte libro — 2025",
    "Planeta Funda eReader — regalo",
    "Planeta Funda eReader — español",
    "Planeta Funda eReader — A5",
    "Planeta Funda eReader — bolsillo",
    "Planeta Funda eReader — tapa dura",
    "Planeta Funda eReader — audiolibro",
    "Planeta Funda eReader — pack 3",
    "Planeta Funda eReader — 2025",
    "Planeta Cuaderno A5 — regalo",
    "Planeta Cuaderno A5 — español",
    "Planeta Cuaderno A5 — A5",
    "Planeta Cuaderno A5 — bolsillo",
    "Planeta Cuaderno A5 — tapa dura",
    "Planeta Cuaderno A5 — audiolibro",
    "Planeta Cuaderno A5 — pack 3",
    "Planeta Cuaderno A5 — 2025",
    "Planeta Pack clásicos — regalo",
    "Planeta Pack clásicos — español"
  ],
  "bebes-ninos": [
    "Philips Avent Chupete 2 uds — 0-6m",
    "Philips Avent Chupete 2 uds — 6-18m",
    "Philips Avent Chupete 2 uds — rosa",
    "Philips Avent Chupete 2 uds — azul",
    "Philips Avent Chupete 2 uds — BPA free",
    "Philips Avent Chupete 2 uds — pack 2",
    "Philips Avent Chupete 2 uds — neutro",
    "Philips Avent Chupete 2 uds — lavable",
    "Philips Avent Biberón anticólico — 0-6m",
    "Philips Avent Biberón anticólico — 6-18m",
    "Philips Avent Biberón anticólico — rosa",
    "Philips Avent Biberón anticólico — azul",
    "Philips Avent Biberón anticólico — BPA free",
    "Philips Avent Biberón anticólico — pack 2",
    "Philips Avent Biberón anticólico — neutro",
    "Philips Avent Biberón anticólico — lavable",
    "Philips Avent Termómetro baño — 0-6m",
    "Philips Avent Termómetro baño — 6-18m",
    "Philips Avent Termómetro baño — rosa",
    "Philips Avent Termómetro baño — azul",
    "Philips Avent Termómetro baño — BPA free",
    "Philips Avent Termómetro baño — pack 2",
    "Philips Avent Termómetro baño — neutro",
    "Philips Avent Termómetro baño — lavable",
    "Philips Avent Sábana cuna — 0-6m",
    "Philips Avent Sábana cuna — 6-18m",
    "Philips Avent Sábana cuna — rosa",
    "Philips Avent Sábana cuna — azul",
    "Philips Avent Sábana cuna — BPA free",
    "Philips Avent Sábana cuna — pack 2",
    "Philips Avent Sábana cuna — neutro",
    "Philips Avent Sábana cuna — lavable",
    "Philips Avent Reducidor wc — 0-6m",
    "Philips Avent Reducidor wc — 6-18m",
    "Philips Avent Reducidor wc — rosa",
    "Philips Avent Reducidor wc — azul",
    "Philips Avent Reducidor wc — BPA free",
    "Philips Avent Reducidor wc — pack 2",
    "Philips Avent Reducidor wc — neutro",
    "Philips Avent Reducidor wc — lavable",
    "Philips Avent Mordedor silicona — 0-6m",
    "Philips Avent Mordedor silicona — 6-18m"
  ],
  "juguetes": [
    "LEGO Caja almacenaje — 6+",
    "LEGO Caja almacenaje — 8+",
    "LEGO Caja almacenaje — negro",
    "LEGO Caja almacenaje — pack",
    "LEGO Caja almacenaje — oficial",
    "LEGO Caja almacenaje — compatible",
    "LEGO Caja almacenaje — recargable",
    "LEGO Caja almacenaje — regalo",
    "LEGO Baseplate — 6+",
    "LEGO Baseplate — 8+",
    "LEGO Baseplate — negro",
    "LEGO Baseplate — pack",
    "LEGO Baseplate — oficial",
    "LEGO Baseplate — compatible",
    "LEGO Baseplate — recargable",
    "LEGO Baseplate — regalo",
    "LEGO Puzzle 500p — 6+",
    "LEGO Puzzle 500p — 8+",
    "LEGO Puzzle 500p — negro",
    "LEGO Puzzle 500p — pack",
    "LEGO Puzzle 500p — oficial",
    "LEGO Puzzle 500p — compatible",
    "LEGO Puzzle 500p — recargable",
    "LEGO Puzzle 500p — regalo",
    "LEGO Pilas recargables — 6+",
    "LEGO Pilas recargables — 8+",
    "LEGO Pilas recargables — negro",
    "LEGO Pilas recargables — pack",
    "LEGO Pilas recargables — oficial",
    "LEGO Pilas recargables — compatible",
    "LEGO Pilas recargables — recargable",
    "LEGO Pilas recargables — regalo",
    "LEGO Organizador piezas — 6+",
    "LEGO Organizador piezas — 8+",
    "LEGO Organizador piezas — negro",
    "LEGO Organizador piezas — pack",
    "LEGO Organizador piezas — oficial",
    "LEGO Organizador piezas — compatible",
    "LEGO Organizador piezas — recargable",
    "LEGO Organizador piezas — regalo",
    "LEGO Estuche cartas — 6+",
    "LEGO Estuche cartas — 8+"
  ],
  "mascotas": [
    "Royal Canin Bol plegable — perro M",
    "Royal Canin Bol plegable — gato",
    "Royal Canin Bol plegable — pack",
    "Royal Canin Bol plegable — hipoalergénico",
    "Royal Canin Bol plegable — recambio",
    "Royal Canin Bol plegable — viaje",
    "Royal Canin Bol plegable — senior",
    "Royal Canin Bol plegable — cachorro",
    "Royal Canin Cepillo deshedding — perro M",
    "Royal Canin Cepillo deshedding — gato",
    "Royal Canin Cepillo deshedding — pack",
    "Royal Canin Cepillo deshedding — hipoalergénico",
    "Royal Canin Cepillo deshedding — recambio",
    "Royal Canin Cepillo deshedding — viaje",
    "Royal Canin Cepillo deshedding — senior",
    "Royal Canin Cepillo deshedding — cachorro",
    "Royal Canin Arena 10L — perro M",
    "Royal Canin Arena 10L — gato",
    "Royal Canin Arena 10L — pack",
    "Royal Canin Arena 10L — hipoalergénico",
    "Royal Canin Arena 10L — recambio",
    "Royal Canin Arena 10L — viaje",
    "Royal Canin Arena 10L — senior",
    "Royal Canin Arena 10L — cachorro",
    "Royal Canin Correa extensible — perro M",
    "Royal Canin Correa extensible — gato",
    "Royal Canin Correa extensible — pack",
    "Royal Canin Correa extensible — hipoalergénico",
    "Royal Canin Correa extensible — recambio",
    "Royal Canin Correa extensible — viaje",
    "Royal Canin Correa extensible — senior",
    "Royal Canin Correa extensible — cachorro",
    "Royal Canin Fuente filtro — perro M",
    "Royal Canin Fuente filtro — gato",
    "Royal Canin Fuente filtro — pack",
    "Royal Canin Fuente filtro — hipoalergénico",
    "Royal Canin Fuente filtro — recambio",
    "Royal Canin Fuente filtro — viaje",
    "Royal Canin Fuente filtro — senior",
    "Royal Canin Fuente filtro — cachorro",
    "Royal Canin Transportín — perro M",
    "Royal Canin Transportín — gato"
  ],
  "automovil": [
    "Michelin Limpiaparabrisas 5L — universal",
    "Michelin Limpiaparabrisas 5L — 12V",
    "Michelin Limpiaparabrisas 5L — USB-C",
    "Michelin Limpiaparabrisas 5L — negro",
    "Michelin Limpiaparabrisas 5L — verano",
    "Michelin Limpiaparabrisas 5L — invierno",
    "Michelin Limpiaparabrisas 5L — pack",
    "Michelin Limpiaparabrisas 5L — OBD",
    "Michelin Organizador maletero — universal",
    "Michelin Organizador maletero — 12V",
    "Michelin Organizador maletero — USB-C",
    "Michelin Organizador maletero — negro",
    "Michelin Organizador maletero — verano",
    "Michelin Organizador maletero — invierno",
    "Michelin Organizador maletero — pack",
    "Michelin Organizador maletero — OBD",
    "Michelin Cargador coche 65W — universal",
    "Michelin Cargador coche 65W — 12V",
    "Michelin Cargador coche 65W — USB-C",
    "Michelin Cargador coche 65W — negro",
    "Michelin Cargador coche 65W — verano",
    "Michelin Cargador coche 65W — invierno",
    "Michelin Cargador coche 65W — pack",
    "Michelin Cargador coche 65W — OBD",
    "Michelin Soporte móvil — universal",
    "Michelin Soporte móvil — 12V",
    "Michelin Soporte móvil — USB-C",
    "Michelin Soporte móvil — negro",
    "Michelin Soporte móvil — verano",
    "Michelin Soporte móvil — invierno",
    "Michelin Soporte móvil — pack",
    "Michelin Soporte móvil — OBD",
    "Michelin Kit detailing — universal",
    "Michelin Kit detailing — 12V",
    "Michelin Kit detailing — USB-C",
    "Michelin Kit detailing — negro",
    "Michelin Kit detailing — verano",
    "Michelin Kit detailing — invierno",
    "Michelin Kit detailing — pack",
    "Michelin Kit detailing — OBD",
    "Michelin Medidor presión — universal",
    "Michelin Medidor presión — 12V"
  ],
  "movilidad": [
    "Xiaomi Candado U — M",
    "Xiaomi Candado U — L",
    "Xiaomi Candado U — negro",
    "Xiaomi Candado U — recargable",
    "Xiaomi Candado U — bici",
    "Xiaomi Candado U — patinete",
    "Xiaomi Candado U — antirrobo",
    "Xiaomi Candado U — USB",
    "Xiaomi Luz delantera — M",
    "Xiaomi Luz delantera — L",
    "Xiaomi Luz delantera — negro",
    "Xiaomi Luz delantera — recargable",
    "Xiaomi Luz delantera — bici",
    "Xiaomi Luz delantera — patinete",
    "Xiaomi Luz delantera — antirrobo",
    "Xiaomi Luz delantera — USB",
    "Xiaomi Casco urbano — M",
    "Xiaomi Casco urbano — L",
    "Xiaomi Casco urbano — negro",
    "Xiaomi Casco urbano — recargable",
    "Xiaomi Casco urbano — bici",
    "Xiaomi Casco urbano — patinete",
    "Xiaomi Casco urbano — antirrobo",
    "Xiaomi Casco urbano — USB",
    "Xiaomi Kit parche — M",
    "Xiaomi Kit parche — L",
    "Xiaomi Kit parche — negro",
    "Xiaomi Kit parche — recargable",
    "Xiaomi Kit parche — bici",
    "Xiaomi Kit parche — patinete",
    "Xiaomi Kit parche — antirrobo",
    "Xiaomi Kit parche — USB",
    "Xiaomi Bomba mini — M",
    "Xiaomi Bomba mini — L",
    "Xiaomi Bomba mini — negro",
    "Xiaomi Bomba mini — recargable",
    "Xiaomi Bomba mini — bici",
    "Xiaomi Bomba mini — patinete",
    "Xiaomi Bomba mini — antirrobo",
    "Xiaomi Bomba mini — USB",
    "Xiaomi Portabotellas — M",
    "Xiaomi Portabotellas — L"
  ],
  "cafe-te": [
    "Hario Filtros V60 100 — V60",
    "Hario Filtros V60 100 — Moka 6",
    "Hario Filtros V60 100 — pack 100",
    "Hario Filtros V60 100 — descafeinado",
    "Hario Filtros V60 100 — orgánico",
    "Hario Filtros V60 100 — regalo",
    "Hario Filtros V60 100 — acero",
    "Hario Filtros V60 100 — cristal",
    "Hario Molinillo manual — V60",
    "Hario Molinillo manual — Moka 6",
    "Hario Molinillo manual — pack 100",
    "Hario Molinillo manual — descafeinado",
    "Hario Molinillo manual — orgánico",
    "Hario Molinillo manual — regalo",
    "Hario Molinillo manual — acero",
    "Hario Molinillo manual — cristal",
    "Hario Termo café — V60",
    "Hario Termo café — Moka 6",
    "Hario Termo café — pack 100",
    "Hario Termo café — descafeinado",
    "Hario Termo café — orgánico",
    "Hario Termo café — regalo",
    "Hario Termo café — acero",
    "Hario Termo café — cristal",
    "Hario Cápsulas compatibles — V60",
    "Hario Cápsulas compatibles — Moka 6",
    "Hario Cápsulas compatibles — pack 100",
    "Hario Cápsulas compatibles — descafeinado",
    "Hario Cápsulas compatibles — orgánico",
    "Hario Cápsulas compatibles — regalo",
    "Hario Cápsulas compatibles — acero",
    "Hario Cápsulas compatibles — cristal",
    "Hario Tetera cristal — V60",
    "Hario Tetera cristal — Moka 6",
    "Hario Tetera cristal — pack 100",
    "Hario Tetera cristal — descafeinado",
    "Hario Tetera cristal — orgánico",
    "Hario Tetera cristal — regalo",
    "Hario Tetera cristal — acero",
    "Hario Tetera cristal — cristal",
    "Hario Infusor té — V60",
    "Hario Infusor té — Moka 6"
  ],
  "vinos-gourmet": [
    "La Chinata Sacacorchos — regalo",
    "La Chinata Sacacorchos — DOP",
    "La Chinata Sacacorchos — 750ml",
    "La Chinata Sacacorchos — ecológico",
    "La Chinata Sacacorchos — pack 3",
    "La Chinata Sacacorchos — DO",
    "La Chinata Sacacorchos — temporada",
    "La Chinata Sacacorchos — gourmet",
    "La Chinata Enfriador vino — regalo",
    "La Chinata Enfriador vino — DOP",
    "La Chinata Enfriador vino — 750ml",
    "La Chinata Enfriador vino — ecológico",
    "La Chinata Enfriador vino — pack 3",
    "La Chinata Enfriador vino — DO",
    "La Chinata Enfriador vino — temporada",
    "La Chinata Enfriador vino — gourmet",
    "La Chinata Copas 2 uds — regalo",
    "La Chinata Copas 2 uds — DOP",
    "La Chinata Copas 2 uds — 750ml",
    "La Chinata Copas 2 uds — ecológico",
    "La Chinata Copas 2 uds — pack 3",
    "La Chinata Copas 2 uds — DO",
    "La Chinata Copas 2 uds — temporada",
    "La Chinata Copas 2 uds — gourmet",
    "La Chinata Aceite AOVE — regalo",
    "La Chinata Aceite AOVE — DOP",
    "La Chinata Aceite AOVE — 750ml",
    "La Chinata Aceite AOVE — ecológico",
    "La Chinata Aceite AOVE — pack 3",
    "La Chinata Aceite AOVE — DO",
    "La Chinata Aceite AOVE — temporada",
    "La Chinata Aceite AOVE — gourmet",
    "La Chinata Jamón ibérico — regalo",
    "La Chinata Jamón ibérico — DOP",
    "La Chinata Jamón ibérico — 750ml",
    "La Chinata Jamón ibérico — ecológico",
    "La Chinata Jamón ibérico — pack 3",
    "La Chinata Jamón ibérico — DO",
    "La Chinata Jamón ibérico — temporada",
    "La Chinata Jamón ibérico — gourmet",
    "La Chinata Cesta regalo — regalo",
    "La Chinata Cesta regalo — DOP"
  ],
  "alimentacion": [
    "Gullón Pack desayuno — sin gluten",
    "Gullón Pack desayuno — vegano",
    "Gullón Pack desayuno — bio",
    "Gullón Pack desayuno — pack 6",
    "Gullón Pack desayuno — 1kg",
    "Gullón Pack desayuno — ahorro",
    "Gullón Pack desayuno — sin lactosa",
    "Gullón Pack desayuno — alto proteína",
    "Gullón Legumbres 4 uds — sin gluten",
    "Gullón Legumbres 4 uds — vegano",
    "Gullón Legumbres 4 uds — bio",
    "Gullón Legumbres 4 uds — pack 6",
    "Gullón Legumbres 4 uds — 1kg",
    "Gullón Legumbres 4 uds — ahorro",
    "Gullón Legumbres 4 uds — sin lactosa",
    "Gullón Legumbres 4 uds — alto proteína",
    "Gullón Aceite oliva 1L — sin gluten",
    "Gullón Aceite oliva 1L — vegano",
    "Gullón Aceite oliva 1L — bio",
    "Gullón Aceite oliva 1L — pack 6",
    "Gullón Aceite oliva 1L — 1kg",
    "Gullón Aceite oliva 1L — ahorro",
    "Gullón Aceite oliva 1L — sin lactosa",
    "Gullón Aceite oliva 1L — alto proteína",
    "Gullón Pasta integral x4 — sin gluten",
    "Gullón Pasta integral x4 — vegano",
    "Gullón Pasta integral x4 — bio",
    "Gullón Pasta integral x4 — pack 6",
    "Gullón Pasta integral x4 — 1kg",
    "Gullón Pasta integral x4 — ahorro",
    "Gullón Pasta integral x4 — sin lactosa",
    "Gullón Pasta integral x4 — alto proteína",
    "Gullón Arroz basmati — sin gluten",
    "Gullón Arroz basmati — vegano",
    "Gullón Arroz basmati — bio",
    "Gullón Arroz basmati — pack 6",
    "Gullón Arroz basmati — 1kg",
    "Gullón Arroz basmati — ahorro",
    "Gullón Arroz basmati — sin lactosa",
    "Gullón Arroz basmati — alto proteína",
    "Gullón Frutos secos 1kg — sin gluten",
    "Gullón Frutos secos 1kg — vegano"
  ],
  "manualidades": [
    "Cricut Vinilo HTV 5 — A4",
    "Cricut Vinilo HTV 5 — A3",
    "Cricut Vinilo HTV 5 — pack",
    "Cricut Vinilo HTV 5 — principiante",
    "Cricut Vinilo HTV 5 — pro",
    "Cricut Vinilo HTV 5 — colores",
    "Cricut Vinilo HTV 5 — craft",
    "Cricut Vinilo HTV 5 — español",
    "Cricut Rotuladores 24 — A4",
    "Cricut Rotuladores 24 — A3",
    "Cricut Rotuladores 24 — pack",
    "Cricut Rotuladores 24 — principiante",
    "Cricut Rotuladores 24 — pro",
    "Cricut Rotuladores 24 — colores",
    "Cricut Rotuladores 24 — craft",
    "Cricut Rotuladores 24 — español",
    "Cricut Lienzo 40x50 — A4",
    "Cricut Lienzo 40x50 — A3",
    "Cricut Lienzo 40x50 — pack",
    "Cricut Lienzo 40x50 — principiante",
    "Cricut Lienzo 40x50 — pro",
    "Cricut Lienzo 40x50 — colores",
    "Cricut Lienzo 40x50 — craft",
    "Cricut Lienzo 40x50 — español",
    "Cricut Hilo mouliné — A4",
    "Cricut Hilo mouliné — A3",
    "Cricut Hilo mouliné — pack",
    "Cricut Hilo mouliné — principiante",
    "Cricut Hilo mouliné — pro",
    "Cricut Hilo mouliné — colores",
    "Cricut Hilo mouliné — craft",
    "Cricut Hilo mouliné — español",
    "Cricut Cutting mat A3 — A4",
    "Cricut Cutting mat A3 — A3",
    "Cricut Cutting mat A3 — pack",
    "Cricut Cutting mat A3 — principiante",
    "Cricut Cutting mat A3 — pro",
    "Cricut Cutting mat A3 — colores",
    "Cricut Cutting mat A3 — craft",
    "Cricut Cutting mat A3 — español",
    "Cricut Resina epoxi — A4",
    "Cricut Resina epoxi — A3"
  ],
  "instrumentos": [
    "Yamaha Cuerdas guitarra — 091",
    "Yamaha Cuerdas guitarra — 046",
    "Yamaha Cuerdas guitarra — 3m",
    "Yamaha Cuerdas guitarra — negro",
    "Yamaha Cuerdas guitarra — natural",
    "Yamaha Cuerdas guitarra — pack",
    "Yamaha Cuerdas guitarra — principiante",
    "Yamaha Cuerdas guitarra — estudio",
    "Yamaha Púas pack 24 — 091",
    "Yamaha Púas pack 24 — 046",
    "Yamaha Púas pack 24 — 3m",
    "Yamaha Púas pack 24 — negro",
    "Yamaha Púas pack 24 — natural",
    "Yamaha Púas pack 24 — pack",
    "Yamaha Púas pack 24 — principiante",
    "Yamaha Púas pack 24 — estudio",
    "Yamaha Correa cuero — 091",
    "Yamaha Correa cuero — 046",
    "Yamaha Correa cuero — 3m",
    "Yamaha Correa cuero — negro",
    "Yamaha Correa cuero — natural",
    "Yamaha Correa cuero — pack",
    "Yamaha Correa cuero — principiante",
    "Yamaha Correa cuero — estudio",
    "Yamaha Afinador clip — 091",
    "Yamaha Afinador clip — 046",
    "Yamaha Afinador clip — 3m",
    "Yamaha Afinador clip — negro",
    "Yamaha Afinador clip — natural",
    "Yamaha Afinador clip — pack",
    "Yamaha Afinador clip — principiante",
    "Yamaha Afinador clip — estudio",
    "Yamaha Cable jack 3m — 091",
    "Yamaha Cable jack 3m — 046",
    "Yamaha Cable jack 3m — 3m",
    "Yamaha Cable jack 3m — negro",
    "Yamaha Cable jack 3m — natural",
    "Yamaha Cable jack 3m — pack",
    "Yamaha Cable jack 3m — principiante",
    "Yamaha Cable jack 3m — estudio",
    "Yamaha Atril plegable — 091",
    "Yamaha Atril plegable — 046"
  ],
  "impresion": [
    "HP Toner negro — XL",
    "HP Toner negro — compatible",
    "HP Toner negro — original",
    "HP Toner negro — A4",
    "HP Toner negro — 500 hojas",
    "HP Toner negro — pack 2",
    "HP Toner negro — oficina",
    "HP Toner negro — hogar",
    "HP Cartucho tricolor — XL",
    "HP Cartucho tricolor — compatible",
    "HP Cartucho tricolor — original",
    "HP Cartucho tricolor — A4",
    "HP Cartucho tricolor — 500 hojas",
    "HP Cartucho tricolor — pack 2",
    "HP Cartucho tricolor — oficina",
    "HP Cartucho tricolor — hogar",
    "HP Papel A4 5000 — XL",
    "HP Papel A4 5000 — compatible",
    "HP Papel A4 5000 — original",
    "HP Papel A4 5000 — A4",
    "HP Papel A4 5000 — 500 hojas",
    "HP Papel A4 5000 — pack 2",
    "HP Papel A4 5000 — oficina",
    "HP Papel A4 5000 — hogar",
    "HP Papel foto 100 — XL",
    "HP Papel foto 100 — compatible",
    "HP Papel foto 100 — original",
    "HP Papel foto 100 — A4",
    "HP Papel foto 100 — 500 hojas",
    "HP Papel foto 100 — pack 2",
    "HP Papel foto 100 — oficina",
    "HP Papel foto 100 — hogar",
    "HP Sobres DL — XL",
    "HP Sobres DL — compatible",
    "HP Sobres DL — original",
    "HP Sobres DL — A4",
    "HP Sobres DL — 500 hojas",
    "HP Sobres DL — pack 2",
    "HP Sobres DL — oficina",
    "HP Sobres DL — hogar",
    "HP Etiquetas A4 — XL",
    "HP Etiquetas A4 — compatible"
  ],
  "colchones": [
    "Emma Almohada visco — 90",
    "Emma Almohada visco — 135",
    "Emma Almohada visco — 150",
    "Emma Almohada visco — 180",
    "Emma Almohada visco — invierno",
    "Emma Almohada visco — verano",
    "Emma Almohada visco — algodón",
    "Emma Almohada visco — pack 2",
    "Emma Protector colchón — 90",
    "Emma Protector colchón — 135",
    "Emma Protector colchón — 150",
    "Emma Protector colchón — 180",
    "Emma Protector colchón — invierno",
    "Emma Protector colchón — verano",
    "Emma Protector colchón — algodón",
    "Emma Protector colchón — pack 2",
    "Emma Sábanas algodón — 90",
    "Emma Sábanas algodón — 135",
    "Emma Sábanas algodón — 150",
    "Emma Sábanas algodón — 180",
    "Emma Sábanas algodón — invierno",
    "Emma Sábanas algodón — verano",
    "Emma Sábanas algodón — algodón",
    "Emma Sábanas algodón — pack 2",
    "Emma Nórdico invierno — 90",
    "Emma Nórdico invierno — 135",
    "Emma Nórdico invierno — 150",
    "Emma Nórdico invierno — 180",
    "Emma Nórdico invierno — invierno",
    "Emma Nórdico invierno — verano",
    "Emma Nórdico invierno — algodón",
    "Emma Nórdico invierno — pack 2",
    "Emma Topper visco — 90",
    "Emma Topper visco — 135",
    "Emma Topper visco — 150",
    "Emma Topper visco — 180",
    "Emma Topper visco — invierno",
    "Emma Topper visco — verano",
    "Emma Topper visco — algodón",
    "Emma Topper visco — pack 2",
    "Emma Funda nórdica — 90",
    "Emma Funda nórdica — 135"
  ],
  "electronica": [
    "Anker Powerbank 20000 — USB-C",
    "Anker Powerbank 20000 — 65W",
    "Anker Powerbank 20000 — 100W",
    "Anker Powerbank 20000 — MagSafe",
    "Anker Powerbank 20000 — GaN",
    "Anker Powerbank 20000 — negro",
    "Anker Powerbank 20000 — blanco",
    "Anker Powerbank 20000 — pack 2",
    "Anker Cargador GaN 65W — USB-C",
    "Anker Cargador GaN 65W — 65W",
    "Anker Cargador GaN 65W — 100W",
    "Anker Cargador GaN 65W — MagSafe",
    "Anker Cargador GaN 65W — GaN",
    "Anker Cargador GaN 65W — negro",
    "Anker Cargador GaN 65W — blanco",
    "Anker Cargador GaN 65W — pack 2",
    "Anker Cable USB-C pack — USB-C",
    "Anker Cable USB-C pack — 65W",
    "Anker Cable USB-C pack — 100W",
    "Anker Cable USB-C pack — MagSafe",
    "Anker Cable USB-C pack — GaN",
    "Anker Cable USB-C pack — negro",
    "Anker Cable USB-C pack — blanco",
    "Anker Cable USB-C pack — pack 2",
    "Anker Hub HDMI — USB-C",
    "Anker Hub HDMI — 65W",
    "Anker Hub HDMI — 100W",
    "Anker Hub HDMI — MagSafe",
    "Anker Hub HDMI — GaN",
    "Anker Hub HDMI — negro",
    "Anker Hub HDMI — blanco",
    "Anker Hub HDMI — pack 2",
    "Anker Localizador Tile — USB-C",
    "Anker Localizador Tile — 65W",
    "Anker Localizador Tile — 100W",
    "Anker Localizador Tile — MagSafe",
    "Anker Localizador Tile — GaN",
    "Anker Localizador Tile — negro",
    "Anker Localizador Tile — blanco",
    "Anker Localizador Tile — pack 2",
    "Anker Estación carga 3 en 1 — USB-C",
    "Anker Estación carga 3 en 1 — 65W"
  ]
};

export function buildCatalog9Products(existingNames = new Set()) {
  return buildCatalogFromNames({
    namesByCategory: NAMES,
    meta: CAT_META,
    idPrefix: "c9",
    existingNames,
  });
}
